In [1]:
import json
import os
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table("../data/NV2g.20240221.geneNames.txt", index_col="id")
df = df.dropna(subset=["name"])
df.head()

,main_id,name,sym,source_id,oma_group_id
id,,,,,
NV2t009957001.1,SELF,NV2t009957001.1,NaN,0,0
NV2t005400001.1,SELF,aurora kinase A,AURKA,OMA|OrthologousGroup|HUMAN|ENSG00000087586,OMAGROUP|OGNone
NV2t011205001.1,SELF,KAT8 regulatory NSL complex subunit 1,KANSL1,OMA|1to1|ENS|HUMAN|ENSG00000120071,OMAGROUP|OG1052381
NV2t014228001.1,SELF,Filamin-A,Flna,UNIPROT|Mus musculus|Q8BTM8|6.66e-07,0
NV2t006138001.1,SELF,Derived by automated computational analysis us...,0,OMA|1to1|MultiGroup|MULTI|OG845447(HAECO17377)...,"OMAGROUP|OGMULTI|OG845447(HAECO17377),OG845447..."

In [3]:
folds_dir = "/Users/jonathanzhu/Downloads/folds"
files = os.listdir(folds_dir)
files = [f for f in files if (".zip" not in f and ".DS_Store" not in f)]
files

['folds_2026_10_13_16_24',
 'folds_2026_10_13_16_25',
 'folds_2026_10_13_16_26 (1)',
 'folds_2026_10_13_16_27 (1)',
 'folds_2026_10_13_16_27',
 'folds_2026_10_13_16_26']

In [4]:
names = []
iptms = []
ptms = []
ranking_scores = []
fraction_disordered = []
has_clash = []
chain_iptm_1 = []
chain_iptm_2 = []
chain_ptm_1 = []
chain_ptm_2 = []
chain_pair_iptm_1a = []
chain_pair_iptm_1b = []
chain_pair_iptm_2a = []
chain_pair_iptm_2b = []
chain_pair_pae_1a = []
chain_pair_pae_1b = []
chain_pair_pae_2a = []
chain_pair_pae_2b = []


for f in files:
    current_jobs = os.listdir(folds_dir + "/" + f)
    current_jobs = [c for c in current_jobs if (".md" not in c and ".DS_Store" not in c)]

    for c in current_jobs:
        current_json = folds_dir + "/" + f + "/" + c + "/fold_" + c + "_summary_confidences_0.json"
        names.append(c)
        with open(current_json, 'r') as fr:
            data = json.load(fr)
        iptms.append(data["iptm"])
        ptms.append(data["ptm"])
        ranking_scores.append(data['ranking_score'])
        fraction_disordered.append(data['fraction_disordered'])
        has_clash.append(data['has_clash'])

        #assertions: need to make sure structure of these is same across all. 
        #they should be but just in case
        assert len(data['chain_iptm']) == 2
        assert len(data['chain_ptm']) == 2
        assert len(data['chain_pair_iptm']) == 2
        assert len(data['chain_pair_pae_min']) == 2
        assert len(data['chain_pair_iptm'][0]) == 2
        assert len(data['chain_pair_iptm'][1]) == 2
        assert len(data['chain_pair_pae_min'][0]) == 2
        assert len(data['chain_pair_pae_min'][1]) == 2

        chain_iptm_1.append(data['chain_iptm'][0])
        chain_iptm_2.append(data['chain_iptm'][1])
        chain_ptm_1.append(data['chain_ptm'][0])
        chain_ptm_2.append(data['chain_ptm'][1])
        chain_pair_iptm_1a.append(data['chain_pair_iptm'][0][0])
        chain_pair_iptm_1b.append(data['chain_pair_iptm'][0][1])
        chain_pair_iptm_2a.append(data['chain_pair_iptm'][1][0])
        chain_pair_iptm_2b.append(data['chain_pair_iptm'][1][1])
        chain_pair_pae_1a.append(data['chain_pair_pae_min'][0][0])
        chain_pair_pae_1b.append(data['chain_pair_pae_min'][0][1])
        chain_pair_pae_2a.append(data['chain_pair_pae_min'][1][0])
        chain_pair_pae_2b.append(data['chain_pair_pae_min'][1][1])

results = pd.DataFrame({'names': names,
                        'iptm': iptms,
                        'ptm': ptms,
                        'ranking_score': ranking_scores,
                        'fraction_disordered': fraction_disordered,
                        'has_clash': has_clash,
                        'chain_iptm_1': chain_iptm_1,
                        'chain_iptm_2': chain_iptm_2,
                        'chain_ptm_1': chain_ptm_1,
                        'chain_ptm_2': chain_ptm_2,
                        'chain_pair_iptm_1a': chain_pair_iptm_1a,
                        'chain_pair_iptm_1b': chain_pair_iptm_1b,
                        'chain_pair_iptm_2a': chain_pair_iptm_2a,
                        'chain_pair_iptm_2b': chain_pair_iptm_2b,
                        'chain_pair_pae_1a': chain_pair_pae_1a,
                        'chain_pair_pae_1b': chain_pair_pae_1b,
                        'chain_pair_pae_2a': chain_pair_pae_2a,
                        'chain_pair_pae_2b': chain_pair_pae_2b})

In [5]:
results.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
0,nv2t018388001_glw6,0.33,0.73,0.47,0.11,0.0,0.33,0.33,0.01,0.74,0.01,0.33,0.33,0.74,0.77,18.56,18.70,0.76
1,nv2t001904001_glw6,0.31,0.55,0.49,0.27,0.0,0.31,0.31,0.01,0.56,0.01,0.31,0.31,0.56,0.76,14.43,15.06,0.76
2,nv2t018451001_glw6,0.55,0.60,0.72,0.31,0.0,0.55,0.55,0.01,0.60,0.01,0.55,0.55,0.60,0.76,9.47,8.22,0.76
3,nv2t000801001_glw6,0.51,0.42,0.53,0.08,0.0,0.51,0.51,0.01,0.43,0.01,0.51,0.51,0.43,0.77,16.16,14.22,0.76
4,nv2t019392002_glw6,0.53,0.76,0.64,0.12,0.0,0.53,0.53,0.01,0.76,0.01,0.53,0.53,0.76,0.77,14.40,12.38,0.76

In [6]:
results.to_csv("results_GLW6.csv")

In [7]:
results_sorted = results.sort_values(by=["ptm", "iptm"], ascending=False)
results_sorted.to_csv("sorted_results_GLW6.csv")
results_sorted.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
84,nv2t009631001_glw6,0.43,0.83,0.54,0.07,0.0,0.43,0.43,0.02,0.84,0.02,0.43,0.43,0.84,0.76,10.73,10.22,0.76
67,nv2t004862001_glw6,0.69,0.82,0.74,0.04,0.0,0.69,0.69,0.01,0.82,0.01,0.69,0.69,0.82,0.76,8.17,5.79,0.76
121,nv2t013314002_glw6,0.91,0.81,0.97,0.17,0.0,0.91,0.91,0.03,0.81,0.03,0.91,0.91,0.81,0.76,1.50,1.22,0.76
28,nv2t018839001_glw6,0.70,0.81,0.78,0.11,0.0,0.70,0.70,0.02,0.81,0.02,0.70,0.70,0.81,0.76,6.88,4.14,0.76
130,nv2t017448002_glw6,0.45,0.81,0.60,0.15,0.0,0.45,0.45,0.02,0.81,0.02,0.45,0.45,0.81,0.77,8.94,7.12,0.76

In [8]:
results_iptm_sorted = results.sort_values(by=["iptm", "ptm"], ascending=False)
results_iptm_sorted.to_csv("sorted_iptm_results_GLW6.csv")
results_iptm_sorted.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
121,nv2t013314002_glw6,0.91,0.81,0.97,0.17,0.0,0.91,0.91,0.03,0.81,0.03,0.91,0.91,0.81,0.76,1.50,1.22,0.76
124,nv2t013314001_glw6,0.91,0.80,0.97,0.17,0.0,0.91,0.91,0.03,0.80,0.03,0.91,0.91,0.80,0.76,1.51,1.22,0.76
81,nv2t005982001_glw6,0.82,0.80,0.89,0.14,0.0,0.82,0.82,0.02,0.80,0.02,0.82,0.82,0.80,0.76,1.51,1.18,0.76
89,nv2t007513001_glw6,0.80,0.63,0.83,0.12,0.0,0.80,0.80,0.02,0.63,0.02,0.80,0.80,0.63,0.76,6.00,4.55,0.76
47,nv2t019392001_glw6,0.79,0.79,0.85,0.11,0.0,0.79,0.79,0.02,0.79,0.02,0.79,0.79,0.79,0.76,4.45,4.22,0.76