In [1]:
import json
import os
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table("../data/NV2g.20240221.geneNames.txt", index_col="id")
df = df.dropna(subset=["name"])
df.head()

,main_id,name,sym,source_id,oma_group_id
id,,,,,
NV2t009957001.1,SELF,NV2t009957001.1,NaN,0,0
NV2t005400001.1,SELF,aurora kinase A,AURKA,OMA|OrthologousGroup|HUMAN|ENSG00000087586,OMAGROUP|OGNone
NV2t011205001.1,SELF,KAT8 regulatory NSL complex subunit 1,KANSL1,OMA|1to1|ENS|HUMAN|ENSG00000120071,OMAGROUP|OG1052381
NV2t014228001.1,SELF,Filamin-A,Flna,UNIPROT|Mus musculus|Q8BTM8|6.66e-07,0
NV2t006138001.1,SELF,Derived by automated computational analysis us...,0,OMA|1to1|MultiGroup|MULTI|OG845447(HAECO17377)...,"OMAGROUP|OGMULTI|OG845447(HAECO17377),OG845447..."

In [3]:
folds_dir = "/Users/jonathanzhu/Downloads/folds"
files = os.listdir(folds_dir)
files = [f for f in files if (".zip" not in f and ".DS_Store" not in f)]
files

['folds_2026_10_06_01_00',
 'folds_2026_10_06_01_01',
 'folds_2026_10_06_01_03',
 'folds_2026_10_06_01_04',
 'folds_2026_10_06_01_05',
 'folds_2026_10_06_00_58']

In [4]:
names = []
iptms = []
ptms = []
ranking_scores = []
fraction_disordered = []
has_clash = []
chain_iptm_1 = []
chain_iptm_2 = []
chain_ptm_1 = []
chain_ptm_2 = []
chain_pair_iptm_1a = []
chain_pair_iptm_1b = []
chain_pair_iptm_2a = []
chain_pair_iptm_2b = []
chain_pair_pae_1a = []
chain_pair_pae_1b = []
chain_pair_pae_2a = []
chain_pair_pae_2b = []


for f in files:
    current_jobs = os.listdir(folds_dir + "/" + f)
    current_jobs = [c for c in current_jobs if (".md" not in c and ".DS_Store" not in c)]

    for c in current_jobs:
        current_json = folds_dir + "/" + f + "/" + c + "/fold_" + c + "_summary_confidences_0.json"
        names.append(c)
        with open(current_json, 'r') as fr:
            data = json.load(fr)
        iptms.append(data["iptm"])
        ptms.append(data["ptm"])
        ranking_scores.append(data['ranking_score'])
        fraction_disordered.append(data['fraction_disordered'])
        has_clash.append(data['has_clash'])

        #assertions: need to make sure structure of these is same across all. 
        #they should be but just in case
        assert len(data['chain_iptm']) == 2
        assert len(data['chain_ptm']) == 2
        assert len(data['chain_pair_iptm']) == 2
        assert len(data['chain_pair_pae_min']) == 2
        assert len(data['chain_pair_iptm'][0]) == 2
        assert len(data['chain_pair_iptm'][1]) == 2
        assert len(data['chain_pair_pae_min'][0]) == 2
        assert len(data['chain_pair_pae_min'][1]) == 2

        chain_iptm_1.append(data['chain_iptm'][0])
        chain_iptm_2.append(data['chain_iptm'][1])
        chain_ptm_1.append(data['chain_ptm'][0])
        chain_ptm_2.append(data['chain_ptm'][1])
        chain_pair_iptm_1a.append(data['chain_pair_iptm'][0][0])
        chain_pair_iptm_1b.append(data['chain_pair_iptm'][0][1])
        chain_pair_iptm_2a.append(data['chain_pair_iptm'][1][0])
        chain_pair_iptm_2b.append(data['chain_pair_iptm'][1][1])
        chain_pair_pae_1a.append(data['chain_pair_pae_min'][0][0])
        chain_pair_pae_1b.append(data['chain_pair_pae_min'][0][1])
        chain_pair_pae_2a.append(data['chain_pair_pae_min'][1][0])
        chain_pair_pae_2b.append(data['chain_pair_pae_min'][1][1])

results = pd.DataFrame({'names': names,
                        'iptm': iptms,
                        'ptm': ptms,
                        'ranking_score': ranking_scores,
                        'fraction_disordered': fraction_disordered,
                        'has_clash': has_clash,
                        'chain_iptm_1': chain_iptm_1,
                        'chain_iptm_2': chain_iptm_2,
                        'chain_ptm_1': chain_ptm_1,
                        'chain_ptm_2': chain_ptm_2,
                        'chain_pair_iptm_1a': chain_pair_iptm_1a,
                        'chain_pair_iptm_1b': chain_pair_iptm_1b,
                        'chain_pair_iptm_2a': chain_pair_iptm_2a,
                        'chain_pair_iptm_2b': chain_pair_iptm_2b,
                        'chain_pair_pae_1a': chain_pair_pae_1a,
                        'chain_pair_pae_1b': chain_pair_pae_1b,
                        'chain_pair_pae_2a': chain_pair_pae_2a,
                        'chain_pair_pae_2b': chain_pair_pae_2b})

In [5]:
results.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
0,nv2t019392002,0.54,0.75,0.65,0.13,0.0,0.54,0.54,0.01,0.75,0.01,0.54,0.54,0.75,0.76,13.36,12.04,0.76
1,nv2t018839001,0.53,0.80,0.63,0.10,0.0,0.53,0.53,0.01,0.81,0.01,0.53,0.53,0.81,0.76,8.20,5.31,0.76
2,nv2t000782006,0.09,0.43,0.37,0.43,0.0,0.09,0.09,0.02,0.44,0.02,0.09,0.09,0.44,0.77,18.73,18.14,0.76
3,nv2t000782001,0.42,0.71,0.54,0.12,0.0,0.42,0.42,0.01,0.71,0.01,0.42,0.42,0.71,0.77,10.34,9.32,0.76
4,nv2t013263003,0.21,0.57,0.40,0.23,0.0,0.21,0.21,0.01,0.57,0.01,0.21,0.21,0.57,0.77,25.29,25.81,0.76

In [6]:
results.to_csv("results.csv")

In [9]:
results_sorted = results.sort_values(by=["ptm", "iptm"], ascending=False)
results_sorted.to_csv("sorted_results.csv")
results_sorted.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
104,nv2t009631001,0.38,0.83,0.50,0.06,0.0,0.38,0.38,0.01,0.84,0.01,0.38,0.38,0.84,0.76,11.14,11.56,0.76
55,nv2t004862001,0.64,0.81,0.70,0.06,0.0,0.64,0.64,0.01,0.81,0.01,0.64,0.64,0.81,0.76,8.48,5.82,0.76
48,nv2t013314002,0.84,0.80,0.91,0.16,0.0,0.84,0.84,0.02,0.80,0.02,0.84,0.84,0.80,0.76,1.67,1.29,0.76
1,nv2t018839001,0.53,0.80,0.63,0.10,0.0,0.53,0.53,0.01,0.81,0.01,0.53,0.53,0.81,0.76,8.20,5.31,0.76
27,nv2t017955001,0.33,0.80,0.45,0.05,0.0,0.33,0.33,0.01,0.80,0.01,0.33,0.33,0.80,0.77,18.73,20.35,0.76

In [10]:
results_iptm_sorted = results.sort_values(by=["iptm", "ptm"], ascending=False)
results_iptm_sorted.to_csv("sorted_iptm_results.csv")
results_iptm_sorted.head()

,names,iptm,ptm,ranking_score,fraction_disordered,has_clash,chain_iptm_1,chain_iptm_2,chain_ptm_1,chain_ptm_2,chain_pair_iptm_1a,chain_pair_iptm_1b,chain_pair_iptm_2a,chain_pair_iptm_2b,chain_pair_pae_1a,chain_pair_pae_1b,chain_pair_pae_2a,chain_pair_pae_2b
37,nv2t013314001,0.86,0.79,0.92,0.16,0.0,0.86,0.86,0.02,0.79,0.02,0.86,0.86,0.79,0.76,1.43,1.19,0.76
116,nv2t012744002,0.85,0.69,0.87,0.09,0.0,0.85,0.85,0.02,0.69,0.02,0.85,0.85,0.69,0.76,3.96,3.93,0.76
48,nv2t013314002,0.84,0.80,0.91,0.16,0.0,0.84,0.84,0.02,0.80,0.02,0.84,0.84,0.80,0.76,1.67,1.29,0.76
106,nv2t005982001,0.75,0.79,0.83,0.14,0.0,0.75,0.75,0.02,0.79,0.02,0.75,0.75,0.79,0.76,1.47,1.16,0.76
95,nv2t005624002,0.75,0.43,0.78,0.19,0.0,0.75,0.75,0.01,0.43,0.01,0.75,0.75,0.43,0.76,6.66,4.07,0.76